### ISSUE TITLE
Source Find/Replace does not work in CKEditor 4.19

### ISSUE THREAD

**Issue by stalker780** [w8tcha/CKEditor-CodeMirror-Plugin#197]
When working in Source mode with CodeMirror plugin enabled and pressing Find or Replace toolbar buttons or CTRL+F nothing happens.

![image](https://user-images.githubusercontent.com/6297070/173032332-8082eb6c-6999-4115-ab66-603aa5fe0875.png)

In console there is an error:
`Uncaught TypeError: b.phrase is not a function`
![image](https://user-images.githubusercontent.com/6297070/173032371-6ed17244-0597-467f-a067-d43a4a64a631.png)

CKEditor: 4.19.0
CodeMirror plugin: 1.18.4
Windows 10, Firefox 101, Chrome 102

**Comment by w8tcha** [comment]
On the demo page i cannot reproduce the issue. 

http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoFramed.html

**Comment by stalker780** [comment]
Hmm. Thanks. I will check this. Perhaps some other plugin breaks this functionality.
